kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    project: manoshop
    module: backend
    environment: web
  ports:
  - name: nginx
    protocol: TCP
    port: 80 
    targetPort: 80 